### ISSUE TITLE
selenium调用chrome貌似存在问题

### ISSUE THREAD

**Issue by cooolmooon** [yxKryptonite/FuckPupedu#1]
应该需要另外装个chromedriver，然而即便如此本地运行时依旧出现报错，猜测有一些版本不兼容和安装路径的问题，想请问作者的chrome和chromedriver是怎么安装的呀，以及本地用的什么环境？非常感谢！

**Comment by yxKryptonite** [comment]
我在 `requirements.txt` 中指定了版本号，应该不会出现问题。Chromedriver正常安装chrome浏览器应该就会自带，不需要额外安装。

本地环境是MacOS 12.4，Chrome忘记当时是什么版本了。

btw，这个项目是我年初开发的，自用完就不再维护了，这段时间内博雅云学堂网站前端可能已经发生改变，我不能保证这个项目现在依然可以正常运行。

如果之后依然遇到问题，可以把安装过程和报错信息完整贴上来。

**Comment by cooolmooon** [comment]
非常感谢您的回复！我的本地环境是Windows10+wsl，wsl中使用apt-get安装的chrome包貌似存在一定问题，我之后换个环境再试试吧
